spring.application.name=spring-api-rest
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

##cada que la app se levanta crea la BD a aprtir del modelo definido con JPA
spring.jpa.hibernate.ddl-auto=create-drop
